version: '3.8'

services:
  # Development environment
  app-dev:
    build:
      context: .
      target: development
    container_name: mr-fried-chicken-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - mr-fried-chicken-network

  # Production environment
  app-prod:
    build:
      context: .
      target: production
    container_name: mr-fried-chicken-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mr-fried-chicken-network
    profiles:
      - production

  # Nginx reverse proxy (optional for advanced setups)
  nginx-proxy:
    image: nginx:alpine
    container_name: mr-fried-chicken-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app-prod
    networks:
      - mr-fried-chicken-network
    profiles:
      - proxy

networks:
  mr-fried-chicken-network:
    driver: bridge

volumes:
  node_modules: